// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graph.proto

/*
Package graph is a generated protocol buffer package.

It is generated from these files:
	graph.proto

It has these top-level messages:
	Follow
	Block
*/
package graph

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import messages "github.com/andyleap/social-melange/proto/messages"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Follow struct {
	Follow *messages.Signer `protobuf:"bytes,1,opt,name=Follow" json:"Follow,omitempty"`
}

func (m *Follow) Reset()                    { *m = Follow{} }
func (m *Follow) String() string            { return proto.CompactTextString(m) }
func (*Follow) ProtoMessage()               {}
func (*Follow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Follow) GetFollow() *messages.Signer {
	if m != nil {
		return m.Follow
	}
	return nil
}

type Block struct {
	Block *messages.Signer `protobuf:"bytes,1,opt,name=Block" json:"Block,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Block) GetBlock() *messages.Signer {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*Follow)(nil), "graph.Follow")
	proto.RegisterType((*Block)(nil), "graph.Block")
}

func init() { proto.RegisterFile("graph.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2f, 0x4a, 0x2c,
	0xc8, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0xc4, 0x73, 0x53, 0x8b,
	0x8b, 0x13, 0xd3, 0x53, 0x8b, 0xf5, 0x61, 0x0c, 0x88, 0xbc, 0x92, 0x11, 0x17, 0x9b, 0x5b, 0x7e,
	0x4e, 0x4e, 0x7e, 0xb9, 0x90, 0x06, 0x8c, 0x25, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa0,
	0x07, 0x57, 0x1a, 0x9c, 0x99, 0x9e, 0x97, 0x5a, 0x14, 0x04, 0x95, 0x57, 0xd2, 0xe7, 0x62, 0x75,
	0xca, 0xc9, 0x4f, 0xce, 0x16, 0x52, 0x83, 0x32, 0x70, 0xea, 0x80, 0x48, 0x27, 0xb1, 0x81, 0xed,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x4d, 0x7d, 0x10, 0x9a, 0x00, 0x00, 0x00,
}
