// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/messages.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages/messages.proto

It has these top-level messages:
	Signer
	Feed
	FeedChange
	SignedFeedChange
	Ref
	Item
	SignedItem
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/andyleap/social-melange/proto/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyKind int32

const (
	KeyKind_ED25519 KeyKind = 0
)

var KeyKind_name = map[int32]string{
	0: "ED25519",
}
var KeyKind_value = map[string]int32{
	"ED25519": 0,
}

func (x KeyKind) String() string {
	return proto.EnumName(KeyKind_name, int32(x))
}
func (KeyKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Algo int32

const (
	Algo_SHA3_512 Algo = 0
)

var Algo_name = map[int32]string{
	0: "SHA3_512",
}
var Algo_value = map[string]int32{
	"SHA3_512": 0,
}

func (x Algo) String() string {
	return proto.EnumName(Algo_name, int32(x))
}
func (Algo) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Signer struct {
	Kind KeyKind `protobuf:"varint,1,opt,name=Kind,enum=messages.KeyKind" json:"Kind,omitempty"`
	Key  []byte  `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (m *Signer) Reset()                    { *m = Signer{} }
func (m *Signer) String() string            { return proto.CompactTextString(m) }
func (*Signer) ProtoMessage()               {}
func (*Signer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Signer) GetKind() KeyKind {
	if m != nil {
		return m.Kind
	}
	return KeyKind_ED25519
}

func (m *Signer) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Feed struct {
	Signer *Signer `protobuf:"bytes,1,opt,name=Signer" json:"Signer,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *Feed) Reset()                    { *m = Feed{} }
func (m *Feed) String() string            { return proto.CompactTextString(m) }
func (*Feed) ProtoMessage()               {}
func (*Feed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Feed) GetSigner() *Signer {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *Feed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FeedChange struct {
	Sequence uint64   `protobuf:"varint,1,opt,name=Sequence" json:"Sequence,omitempty"`
	Ref      *Ref     `protobuf:"bytes,2,opt,name=Ref" json:"Ref,omitempty"`
	Delete   []uint64 `protobuf:"varint,3,rep,packed,name=Delete" json:"Delete,omitempty"`
}

func (m *FeedChange) Reset()                    { *m = FeedChange{} }
func (m *FeedChange) String() string            { return proto.CompactTextString(m) }
func (*FeedChange) ProtoMessage()               {}
func (*FeedChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FeedChange) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *FeedChange) GetRef() *Ref {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *FeedChange) GetDelete() []uint64 {
	if m != nil {
		return m.Delete
	}
	return nil
}

type SignedFeedChange struct {
	FeedChange *FeedChange `protobuf:"bytes,1,opt,name=FeedChange" json:"FeedChange,omitempty"`
	Signature  []byte      `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (m *SignedFeedChange) Reset()                    { *m = SignedFeedChange{} }
func (m *SignedFeedChange) String() string            { return proto.CompactTextString(m) }
func (*SignedFeedChange) ProtoMessage()               {}
func (*SignedFeedChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SignedFeedChange) GetFeedChange() *FeedChange {
	if m != nil {
		return m.FeedChange
	}
	return nil
}

func (m *SignedFeedChange) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Ref struct {
	Algo Algo     `protobuf:"varint,1,opt,name=Algo,enum=messages.Algo" json:"Algo,omitempty"`
	Hash []byte   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Name string   `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Tag  []string `protobuf:"bytes,4,rep,name=Tag" json:"Tag,omitempty"`
}

func (m *Ref) Reset()                    { *m = Ref{} }
func (m *Ref) String() string            { return proto.CompactTextString(m) }
func (*Ref) ProtoMessage()               {}
func (*Ref) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Ref) GetAlgo() Algo {
	if m != nil {
		return m.Algo
	}
	return Algo_SHA3_512
}

func (m *Ref) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Ref) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ref) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type Item struct {
	Author  *Signer  `protobuf:"bytes,1,opt,name=Author" json:"Author,omitempty"`
	Message *any.Any `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
	Refs    []*Ref   `protobuf:"bytes,5,rep,name=Refs" json:"Refs,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Item) GetAuthor() *Signer {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Item) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Item) GetRefs() []*Ref {
	if m != nil {
		return m.Refs
	}
	return nil
}

type SignedItem struct {
	Item      *Item  `protobuf:"bytes,1,opt,name=Item" json:"Item,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (m *SignedItem) Reset()                    { *m = SignedItem{} }
func (m *SignedItem) String() string            { return proto.CompactTextString(m) }
func (*SignedItem) ProtoMessage()               {}
func (*SignedItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SignedItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *SignedItem) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Signer)(nil), "messages.Signer")
	proto.RegisterType((*Feed)(nil), "messages.Feed")
	proto.RegisterType((*FeedChange)(nil), "messages.FeedChange")
	proto.RegisterType((*SignedFeedChange)(nil), "messages.SignedFeedChange")
	proto.RegisterType((*Ref)(nil), "messages.Ref")
	proto.RegisterType((*Item)(nil), "messages.Item")
	proto.RegisterType((*SignedItem)(nil), "messages.SignedItem")
	proto.RegisterEnum("messages.KeyKind", KeyKind_name, KeyKind_value)
	proto.RegisterEnum("messages.Algo", Algo_name, Algo_value)
}

func init() { proto.RegisterFile("messages/messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0xe3, 0x6a, 0xeb, 0x8f, 0x71, 0x12, 0xd4, 0x25, 0xa4, 0x22, 0x14, 0xaa, 0x2e, 0x14,
	0x44, 0xa0, 0x16, 0x96, 0xeb, 0x43, 0x8f, 0x6a, 0xdd, 0x92, 0x62, 0x9a, 0xc3, 0xba, 0xa7, 0x5e,
	0xca, 0xc6, 0x1e, 0x4b, 0x02, 0x69, 0x95, 0x5a, 0x12, 0x45, 0xff, 0x7d, 0xd9, 0x5d, 0x7d, 0x41,
	0xc1, 0xb7, 0x99, 0x79, 0xe8, 0xcd, 0xd3, 0x4f, 0x23, 0x78, 0x9d, 0x61, 0x51, 0x88, 0x08, 0x0b,
	0xbf, 0x2d, 0x16, 0xcf, 0xa7, 0xbc, 0xcc, 0xe9, 0xb4, 0xed, 0xef, 0xae, 0x84, 0xac, 0x7d, 0x21,
	0x6b, 0x23, 0xb0, 0x10, 0xc6, 0xbb, 0x24, 0x92, 0x78, 0xa2, 0xef, 0x81, 0x6c, 0x13, 0x79, 0x70,
	0x46, 0xee, 0xc8, 0xbb, 0x0e, 0x5e, 0x2d, 0x3a, 0x87, 0x2d, 0xd6, 0x4a, 0xe0, 0x5a, 0xa6, 0x36,
	0x58, 0x5b, 0xac, 0x9d, 0x17, 0xee, 0xc8, 0xbb, 0xe4, 0xaa, 0x64, 0x1b, 0x20, 0xdf, 0x10, 0x0f,
	0xd4, 0x6b, 0xad, 0xb4, 0xc5, 0x3c, 0xb0, 0x7b, 0x0b, 0x33, 0xe7, 0xed, 0x2a, 0x0a, 0xe4, 0x51,
	0x64, 0xa8, 0x4d, 0x66, 0x5c, 0xd7, 0x4c, 0x00, 0x28, 0x97, 0x2f, 0xb1, 0x90, 0x11, 0xd2, 0x3b,
	0x98, 0xee, 0xf0, 0x4f, 0x85, 0x72, 0x8f, 0xda, 0x8d, 0xf0, 0xae, 0xa7, 0x6f, 0xc1, 0xe2, 0x78,
	0xd4, 0x0f, 0xcf, 0x83, 0xab, 0x7e, 0x09, 0xc7, 0x23, 0x57, 0x0a, 0xbd, 0x85, 0xf1, 0x06, 0x53,
	0x2c, 0xd1, 0xb1, 0x5c, 0xcb, 0x23, 0xbc, 0xe9, 0xd8, 0x11, 0x6c, 0x1d, 0xe0, 0x30, 0x58, 0xf4,
	0x71, 0xb8, 0xb6, 0x09, 0x7e, 0xd3, 0x7b, 0xf6, 0x1a, 0x1f, 0xc6, 0x7b, 0x03, 0x33, 0xe5, 0x24,
	0xca, 0xea, 0x84, 0x0d, 0x8a, 0x7e, 0xc0, 0xf6, 0x3a, 0x20, 0x65, 0x40, 0xc2, 0x34, 0xca, 0x1b,
	0xa0, 0xd7, 0xbd, 0xa9, 0x9a, 0x72, 0xad, 0x29, 0x12, 0x0f, 0xa2, 0x88, 0x1b, 0x0f, 0x5d, 0x77,
	0x74, 0xac, 0x9e, 0x8e, 0xa2, 0xfe, 0x53, 0x44, 0x0e, 0x71, 0x2d, 0x6f, 0xc6, 0x55, 0xc9, 0xfe,
	0x02, 0xf9, 0x5e, 0x62, 0xa6, 0xa8, 0x87, 0x55, 0x19, 0xe7, 0x67, 0xa8, 0x1b, 0x9d, 0x32, 0x98,
	0xfc, 0x30, 0x92, 0xb6, 0x9e, 0x07, 0xd3, 0x85, 0xba, 0x83, 0x50, 0xd6, 0xbc, 0x15, 0xe8, 0x3b,
	0x20, 0x1c, 0x8f, 0x85, 0xf3, 0xd2, 0xb5, 0xfe, 0x87, 0xab, 0x25, 0xf6, 0x08, 0x60, 0x28, 0xea,
	0xf5, 0xcc, 0xc4, 0x68, 0x96, 0x0f, 0x5e, 0x52, 0x4d, 0xb9, 0x89, 0x78, 0x96, 0xd6, 0xfd, 0x2d,
	0x4c, 0x9a, 0x0b, 0xa3, 0x73, 0x98, 0x7c, 0xdd, 0x04, 0xeb, 0xf5, 0xf2, 0x93, 0x7d, 0x71, 0x7f,
	0x63, 0xf0, 0xd1, 0x4b, 0x98, 0xee, 0x1e, 0xc2, 0xd5, 0xef, 0xf5, 0x32, 0xb0, 0x2f, 0x3e, 0xaf,
	0x7e, 0x2d, 0xa3, 0xa4, 0x8c, 0xab, 0xa7, 0xc5, 0x3e, 0xcf, 0x7c, 0x21, 0x0f, 0x75, 0x8a, 0xe2,
	0xd9, 0x2f, 0xf2, 0x7d, 0x22, 0xd2, 0x0f, 0x19, 0xa6, 0xea, 0xfb, 0xf8, 0xfa, 0xb6, 0xbb, 0x7f,
	0xe0, 0x69, 0xac, 0xfb, 0xd5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x98, 0xd7, 0xcd, 0x1f,
	0x03, 0x00, 0x00,
}
