// Code generated by protoc-gen-go. DO NOT EDIT.
// source: local.proto

/*
Package local is a generated protocol buffer package.

It is generated from these files:
	local.proto

It has these top-level messages:
	PublishMessage
*/
package local

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import messages "github.com/andyleap/social-melange/proto/messages"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishMessage struct {
	Feed string         `protobuf:"bytes,1,opt,name=Feed" json:"Feed,omitempty"`
	Item *messages.Item `protobuf:"bytes,2,opt,name=Item" json:"Item,omitempty"`
}

func (m *PublishMessage) Reset()                    { *m = PublishMessage{} }
func (m *PublishMessage) String() string            { return proto.CompactTextString(m) }
func (*PublishMessage) ProtoMessage()               {}
func (*PublishMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PublishMessage) GetFeed() string {
	if m != nil {
		return m.Feed
	}
	return ""
}

func (m *PublishMessage) GetItem() *messages.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*PublishMessage)(nil), "local.PublishMessage")
}

func init() { proto.RegisterFile("local.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0x4e,
	0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0xc4, 0x73, 0x53, 0x8b,
	0x8b, 0x13, 0xd3, 0x53, 0x8b, 0xf5, 0x61, 0x0c, 0x88, 0xbc, 0x92, 0x07, 0x17, 0x5f, 0x40, 0x69,
	0x52, 0x4e, 0x66, 0x71, 0x86, 0x2f, 0x44, 0x42, 0x48, 0x88, 0x8b, 0xc5, 0x2d, 0x35, 0x35, 0x45,
	0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x52, 0xe2, 0x62, 0xf1, 0x2c, 0x49, 0xcd,
	0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd3, 0x83, 0x1b, 0x02, 0x12, 0x0d, 0x02, 0xcb,
	0x25, 0xb1, 0x81, 0x0d, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x2d, 0xff, 0x43, 0x7f,
	0x00, 0x00, 0x00,
}
